### PR TITLE
Add changelog entries for latest patch releases

### PR DESCRIPTION
**Pull request by jpbu**

### CODE REVIEW

**Comment by ghost** [comment]
Do we also need that in the develop branch?

**Comment by MajdT51** [comment]
LGTM

**Comment by jpbu** [comment]
> Do we also need that in the develop branch?

We suspended the develop branch for now and used the main branch as the target since we had a separate upstream review and merge process in the forked repository and the latest changes were only hotfixes. I would suggest to pick up the proper git flow process with develop branch again when new features are developed and the MIW team can directly merge in the tractus-x repository.

**Comment by jpbu** [comment]
@carslen Could you please have a look at this PR and merge it? Thanks in advance!

**Comment by ghost** [comment]
> > Do we also need that in the develop branch?
> 
> We suspended the develop branch for now and used the main branch as the target since we had a separate upstream review and merge process in the forked repository and the latest changes were only hotfixes. I would suggest to pick up the proper git flow process with develop branch again when new features are developed and the MIW team can directly merge in the tractus-x repository.

Thanks for the explanation, makes sense, and content wise the change looks good!

**Pull request merged**
