### PR TITLE
Fix timeout status list credential

### PR DESCRIPTION
**Pull request by MajdT51**
move issuing status list to the main create wallet request. 
increase version

### CODE REVIEW

**Review by jpbu — APPROVED** [review]
Thanks, looks good. I tested and verified the wallet creation, status list and credential revocation locally.

**Comment by MajdT51** [comment]
hello @carslen , could you please merge this hotfix? 
thanks

**Review by carslen — CHANGES_REQUESTED** [review]
Image is missing. Please ensure that required image (tag) is available.

**Review by carslen — APPROVED** [review]

**Comment by carslen** [comment]
Image will be available short after merging...

**Pull request merged**
