### PR TITLE
Fix security issues for MIW Release R3.1.0

### PR DESCRIPTION
**Pull request by mknoopvw**
Following security issues are supposed to be fixed by this -- due to re-run of github actions on the fixing branch then:
- issues regarding outdated 'libssl' -- this should occur once the respective packaging github actions run on branch "main" again
- issues regarding docker images run as root

### CODE REVIEW

**Comment by carslen** [comment]
Dockerfiles look good, but where to find the libssl fix? Did not get it.

**Comment by mknoopvw** [comment]
There were two security issues on branch main regarding too much use of with X509-related requests. Unfortunately, I cannot obtain a recent issue number, maybe due to renaming the repository?
Nonetheless, the security issue numbers I refer to are: #624 and #625
These seemed to emerge from outdated linux images and these images are supposed to be re-created once a certain github action, namely "Build images and push to Github Package", is triggered on a branch as well as main.

I am not 100% sure how to describe these securiy issues without providing proper links to those issues. All apologies for not having those links available.

**Comment by mknoopvw** [comment]
Addendum:

I found the respective findings in the ng-repository:
https://github.com/catenax-ng/tx-managed-identity-wallets/security/code-scanning/624
https://github.com/catenax-ng/tx-managed-identity-wallets/security/code-scanning/625

These findings point to an outdated libssl3 in generated images.
And those images will be re-generated once the respective github action is triggered; at best automatically due to pushed code.

**Review by carslen — APPROVED** [review]

**Comment by carslen** [comment]
Eclipse Contributor Agreement (ECA) check failed. Please ensure, that you are using the email address from your Eclipse Account in Github (or the other way around).

**Comment by carslen** [comment]
ECA check for Committer Maximilian Schmidt failed. I accepted this for now as his commit 2e085bd got reverted with 4d84449. Maximilian will sign ECA for upcoming PRs.

**Pull request merged**
